### ISSUE TITLE
Cell values that contain commas get double quotes added when copy/pasting

### ISSUE THREAD

**Issue by tb-viktor** [quicktype/glide-data-grid#671]
Hi,

We've discovered a problem with copying text values that contain a comma. Quotes get added to the value when copied:

![glide-data-grid-double-quotes](https://user-images.githubusercontent.com/96176911/226339305-cd2e5fe3-a9ef-4b10-b352-9586bf2b4857.gif)

I assume this is some sort of a mechanism to handle commas being delimiters, but when copy/pasting within the table, we would expect the cell values not to be modified. This can be reproduced here: https://glideapps.github.io/glide-data-grid/?path=/story/glide-data-grid-dataeditor-demos--paste-support

Is there a way to disable this behavior?

**Comment by elloodev** [comment]
I'm also interested in removing the double quotes when a value is copied and it contains a comma. I solved the problem when copying/pasting from one column to another by removing the double quotes when pasting the value, but if the value is copied to an excel file, the double quotes are there.

**Comment by sfc-gh-tkojima** [comment]
+1 at least have a configuration option to disable this feature.

**Comment by jassmith** [comment]
This is fixed in main

**Comment by tb-viktor** [comment]
Hi @jassmith thanks for looking into this! The issue has been only partially resolved by the latest release. Quotes still get added when copying from one text cell to another:

![quotes-paste-table-data](https://github.com/quicktype/glide-data-grid/assets/96176911/1f86cd1b-38be-476e-89cb-ffe26adfc3b5)

Can this also be addressed?

**Comment by tb-viktor** [comment]
I see it is fixed in the storybook, but when we get `5.3.0` from npm, it is not fixed there. I made a code sandbox:

https://codesandbox.io/s/winter-sound-zp3dhc?file=/src/App.js

Might need to open it with Firefox, since clipboard permission does not seem to work in Chrome on it.

**Comment by jassmith** [comment]
get the 5.3.1 beta for now. It will go stable soon.
